language: node_js
node_js:
- '12'
env:
  global:
    secure: cJ6UUrdQeYigEZaf/EL2iMnp2y4fA007uSHaChFy6KYAaRkOkq2N5zsUeQzMWfxPeSjuVRawlHKelm5DcpbZ1eyfesZbsyrkcSQI11mFSn4X6I1BxSPhnmYPmWc7CjcbMcM++IDWeTr8nLuTpvT4UO62TeZlgjKkE5zeLhy5cP4IUulIyzuZkHrWgZyFUjrqyWqtEfAC+kty1g1EhYbjTZalQOuwcdmZrdQmvU6fIrzgPICdANbm0prqSUvcImr5bZJMzBKLX4MeqKUcx7CRQWtMhLIkl+Xpq1BFk1Zqomeu1yesojPgDkA0vX92y38WYGVqIrm7eXTtQrFBA/uMmrTJG/cYQzeY0hHEGIvFdiAquhJeOC/TqfdwyUCaxSQC0QnQ8UyFKAlvZtjxsH1QAF6Wl/wLL3+n3C0JzRwEGP55GbEJ4I2Vu5SqoTKbig2wh1SdaO/wRNXnJ0MkrNw6zR6o9h1SrUtf08T5X3s9suyGATT9DT/wOP0RASNw050lcU68QdTE1U9BgFkl93WOrIiWctEihjy7lRaeQ5ymVldjLUKJowaO7U62a47KDk9FN8oocl5ziT/gzVJ51nLjCirfa2VQd/479dCxLKI2vwifn2ew7QquCN4KtQeN8RpKcxfiPEcaaIRm+394pRtZVNv9/aTgEW21IFJvvdVm0t8=
deploy:
  provider: releases
  api_key:
    secure: bQJwJ1f7RV8XGMAgBRdDkGxjRQfS7ZKNcMexL6AtO3cz4sNbPYjxKZ/F8HYuLkduAfgZhgg7Vbs3+9ponxZJR5KynQoN9KVrHCelSOd5lo+H5diBWMkIDbOyujfRlRYoC9FsE4zQ5XxCgCP4LR+VpcFXRsKnuUaDqAH7DwTNAhuFyMdP7uGLY+EaF1ocENTbvQLngQnTuv9vwn9XAhVh4KP8RFlIGItwsJqomT2BVRU7ENz4GcCP+VVy/Xahroj+YzRQk2Cj4kJCEbpUmLd1BNjS1VDyrAVnDPspI8sDBAuEvdSA7I+yVY6TDVXMdWVOoJZp+Yq1I1Q2cIsRUV1LDJg2Ck/AbptUvgsba499zBZ/kAYyQMGM13y02Z3CbmeGddb5Q3qwtmsD/M0ZiwPPFPoMxrXeGtNxj8JPQZw152sSypYLcpv9cTfLuMUjcZzKPrx58RyY6pAsr0NFt+DmixYoA+bPnFxC8ICMHePNq5dQ1t1JL6LVj+WqBn3G2zhcnv6jIDYDrXCvS3+2JHmjjnfI1BrkBrmKxzqZVqczBaP8g4StwIlc3QPEZR4U1G/WDdqrdRPtG5B9VZspOWL+z93ypjnk0g494uXGSwyZssJVTcRr2WxVX6WDiPORRGFB2pnrY5GBikWYxPsq9Auh5gDiuCtkeuKVI4pbfZvXFjk=
  file_glob: true
  file: subime-syntax/build/sublime/*
  skip_cleanup: true
  on:
    tags: true
    repo: Open-MBEE/MSE
before_script:
  - "cd sublime-syntax"
script: "npm run build"
after_deploy:
  - ./sublime-syntax/push-assets.sh
