language: node_js
node_js:
- '12'
env:
  global:
    secure: WvCRl+ABP+e3wg/m/5Dg5IOn4Ck4ow0GhO+2wE3nB4OZqWk1piYJI+da2HBYSsOQvGje5d7tGumSW5BWsDuhmY+hQ0RW+RLQgtkZaxM95yQ7j+CyFlsKso7G9kmpoXTwJ7o9VoxdCj/6sohr/t67eSZdQoU+pfpwFiT0PbB9zFJ4wdjDUPD1HKvHMMGpwCHTtsuPQaLm3pPS74MuoyvusTFKSFrfops+BCB+q5L7WFSX9NfV2OItyoZiTBc9MKP21EIlXAv/Ibycj8hRpyBZibArT6iYcRQHlZmKCp7UGZk/+gPdXfhuYTl+zzaknrfhTi61YUQi4ZDLUtLigvFk4Qq3NgoSpUMZhQwtpSQ7DQ7dkc30lKWZcB7VEGdZxZdQ5QF17Mh/peaNQRSoIO7zsbE2rXk4q9FRTvglX6U6ZEBnDVUnfPVHR0qg3sQ+px5y4s2aGJEcPS2ih65NnulnJfhKf+b9jtnZT8ntJudCoIpco0tthOBjJm1g2qXXODUDfZ3mb1OXj2mQzFyLLOJ20HoiD2TcWU6beiX8GdGudH1EocdTFzrW+e85Ew+kuJ+4SHWdi3bb1ySba56xn9gV/qSa3VV9CP4qIarOOAlxlgKcHLq/OcL1/qqzhoEs84EzsXXisxeEL3h5Pgq7q6+IivwIWlbY69J3TzFAFBdo2II=
deploy:
  provider: releases
  api_key:
    secure: bQJwJ1f7RV8XGMAgBRdDkGxjRQfS7ZKNcMexL6AtO3cz4sNbPYjxKZ/F8HYuLkduAfgZhgg7Vbs3+9ponxZJR5KynQoN9KVrHCelSOd5lo+H5diBWMkIDbOyujfRlRYoC9FsE4zQ5XxCgCP4LR+VpcFXRsKnuUaDqAH7DwTNAhuFyMdP7uGLY+EaF1ocENTbvQLngQnTuv9vwn9XAhVh4KP8RFlIGItwsJqomT2BVRU7ENz4GcCP+VVy/Xahroj+YzRQk2Cj4kJCEbpUmLd1BNjS1VDyrAVnDPspI8sDBAuEvdSA7I+yVY6TDVXMdWVOoJZp+Yq1I1Q2cIsRUV1LDJg2Ck/AbptUvgsba499zBZ/kAYyQMGM13y02Z3CbmeGddb5Q3qwtmsD/M0ZiwPPFPoMxrXeGtNxj8JPQZw152sSypYLcpv9cTfLuMUjcZzKPrx58RyY6pAsr0NFt+DmixYoA+bPnFxC8ICMHePNq5dQ1t1JL6LVj+WqBn3G2zhcnv6jIDYDrXCvS3+2JHmjjnfI1BrkBrmKxzqZVqczBaP8g4StwIlc3QPEZR4U1G/WDdqrdRPtG5B9VZspOWL+z93ypjnk0g494uXGSwyZssJVTcRr2WxVX6WDiPORRGFB2pnrY5GBikWYxPsq9Auh5gDiuCtkeuKVI4pbfZvXFjk=
  file_glob: true
  file: build/sublime/*
  skip_cleanup: true
  on:
    tags: true
    repo: Open-MBEE/MSE
before_script:
  - "cd sublime-syntax"
script: "npm run build"
after_deploy:
  - ./push-assets.sh
