language: node_js
node_js:
- '12'
env:
  global:
    secure: X+AnJNrurkBCdBylWilypRHiVAC/wnjsHrNdaGpIu0K2SJL+bDF8kTqBmwPodgakL5PfAePXm18RmZFgzMDVWzeJMdh0SfwoMYFyuOs4MiVkb/B22x1XVC9YDPYSDBS8yPYFKZJWTT/p7VODqJbxom0OLjiB2iIVtOqUqWpJwig1cvZjouyhdfoW9pu0oo2p9L0/zdvMfwA81qeZ/NC5XBE9f2F9Vt8XkC9A1QuwSSEnRVmrbbHpMn6Vxx55R+4cFwdayxXS2Eg16n39h3elvNXlf8c94tZAetPo2Z2oaBcng5HLDMe6FCNRVGQOknW9NG1lij/Cno5QOZp5KyZ3FoQm0ea0TXeSEr9NNKOdfG/rbMifp+PTrpRWqme+1xJFqAbrzkNbjH173bWGeWXf1wdPYMPwefhf6KzxmcqdUb3bwA2KXZ4mqamtPEdG3chRlMV3eflBhRVxt1tQII2jfPxomtSj44nU4lA3ssobzHZgKdLanxCDbsGdXSfzHikAwCP7oAKNc82b2oSW/vNDpEImeEjHSiMDJJyPfczWdrzEBq5n2iK7mlRI9Zfcy9y+QUl09j+jnXodsMAu0mWeoQpo9daW7jq5cy/k2kuXYCe8FZUxIcjUxn7NMQ6UrXCLca3y3guhCQ8py7907ECx3p5Zo53Itc6Ca84l9m8ihKw=
deploy:
  provider: releases
  api_key:
    secure: bQJwJ1f7RV8XGMAgBRdDkGxjRQfS7ZKNcMexL6AtO3cz4sNbPYjxKZ/F8HYuLkduAfgZhgg7Vbs3+9ponxZJR5KynQoN9KVrHCelSOd5lo+H5diBWMkIDbOyujfRlRYoC9FsE4zQ5XxCgCP4LR+VpcFXRsKnuUaDqAH7DwTNAhuFyMdP7uGLY+EaF1ocENTbvQLngQnTuv9vwn9XAhVh4KP8RFlIGItwsJqomT2BVRU7ENz4GcCP+VVy/Xahroj+YzRQk2Cj4kJCEbpUmLd1BNjS1VDyrAVnDPspI8sDBAuEvdSA7I+yVY6TDVXMdWVOoJZp+Yq1I1Q2cIsRUV1LDJg2Ck/AbptUvgsba499zBZ/kAYyQMGM13y02Z3CbmeGddb5Q3qwtmsD/M0ZiwPPFPoMxrXeGtNxj8JPQZw152sSypYLcpv9cTfLuMUjcZzKPrx58RyY6pAsr0NFt+DmixYoA+bPnFxC8ICMHePNq5dQ1t1JL6LVj+WqBn3G2zhcnv6jIDYDrXCvS3+2JHmjjnfI1BrkBrmKxzqZVqczBaP8g4StwIlc3QPEZR4U1G/WDdqrdRPtG5B9VZspOWL+z93ypjnk0g494uXGSwyZssJVTcRr2WxVX6WDiPORRGFB2pnrY5GBikWYxPsq9Auh5gDiuCtkeuKVI4pbfZvXFjk=
  file_glob: true
  file: build/sublime/*
  skip_cleanup: true
  on:
    tags: true
    repo: Open-MBEE/MSE
before_script:
  - "cd sublime-syntax"
script: "npm run build"
after_deploy:
  - ./push-assets.sh
